### Get All alerts
GET http://{{HTTP_HOST}}:{{HTTP_PORT}}/v0/alerts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NlcyI6IiIsImV4cCI6MTc1Mzg2MjYzOCwicm9sZSI6InZpZXdlciIsInVzZXJuYW1lIjoiYWxpLnNvbHRhbmkifQ.JL94geaMSXFyR8TxKGKPGP4EVyCipsDvByxYXBqDxeM

###
GET http://{{HTTP_HOST}}:{{HTTP_PORT}}/v0/alerts/{{ALERT_ID}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NlcyI6IioiLCJleHAiOjE3NDQwNDEwMjQsInJvbGUiOiJhZG1pbiIsInVzZXJuYW1lIjoiYWRtaW4ifQ.n9I6yeKr4-P7_DuKlNA3TlBVGT9frokZyAsGhubmSiQ

###
GET http://{{HTTP_HOST}}:{{HTTP_PORT}}/v0/alerts/?page=1&pagination=10&status=resolved
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NlcyI6IiIsImV4cCI6MTc1Mzg2MjYzOCwicm9sZSI6InZpZXdlciIsInVzZXJuYW1lIjoiYWxpLnNvbHRhbmkifQ.JL94geaMSXFyR8TxKGKPGP4EVyCipsDvByxYXBqDxeM

###
GET http://{{HTTP_HOST}}:{{HTTP_PORT}}/v0/alerts/firingCount
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NlcyI6IiIsImV4cCI6MTc1Mzg2MjYzOCwicm9sZSI6InZpZXdlciIsInVzZXJuYW1lIjoiYWxpLnNvbHRhbmkifQ.JL94geaMSXFyR8TxKGKPGP4EVyCipsDvByxYXBqDxeM