### Create User with POST request
POST http://{{ HTTP_HOST }}:{{ HTTP_PORT }}/v1/users/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NlcyI6IioiLCJleHAiOjE3NTM2MDE0ODIsInJvbGUiOiJhZG1pbiIsInVzZXJuYW1lIjoiYWRtaW4ifQ.X_OV4EOJ-awJ-60Vx5c34sYQyFH-RSvRicgulaI3JrU

{
  "username": "ali.soltani",
  "firstname" : "ali",
  "lastname": "soltani",
  "password": "ADMINadmin@123#",
  "confirm-password": "ADMINadmin@123#",
  "email": "a@a.com"
}


### Signin and get token
POST http://{{HTTP_HOST}}:{{HTTP_PORT}}/v1/users/signin
Content-Type: application/json

{
  "username": "ali.soltani",
  "password": "ADMINadmin@123#"
}

#{
#  "username": "admin",
#  "password": "uyxOGKB%zE@EDYm%9t9R"
#}

### Verify User
POST http://{{HTTP_HOST}}:{{HTTP_PORT}}/v1/users/verify
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NlcyI6IioiLCJleHAiOjE3NTM2MDE0ODIsInJvbGUiOiJhZG1pbiIsInVzZXJuYW1lIjoiYWRtaW4ifQ.X_OV4EOJ-awJ-60Vx5c34sYQyFH-RSvRicgulaI3JrU

{
  "username": "ali.soltani"
}